### ISSUE TITLE
Bug do deslocamento de células quando projetadas em WGS84

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/GGeohash#2]
Ver [GGeohash/wiki/Estudos-sobre-o-bug-do-deslocamento](https://github.com/osm-codes/GGeohash/wiki/Estudos-sobre-o-bug-do-deslocamento)

e ver issues já postadas sobre o assunto na Colômbia

**Comment by ppKrauss** [comment]
Solução baseada em `ST_Segmentize()`. A função abaixo, `ST_Transform_resilient()`,  assegura uma proporção de pontos mínima para não comprometer demais o resultado da transformação de retas. O resultado pode ainda ser submetido a `ST_Simplify` de tolerância mínima (zero ou tendendo a zero) para eliminar pontos colinerares.

A  "resiliencia" é relativa à escala de visualização da forma, não garantindo em escalas maiores.

Fronteiras políticas podem tomar um valor fixo, `ST_Transform(  ST_Segmentize(g,valor_fixo)  ,srid)`, para *max_segment_length* não comprometer a interseção vazia em mosaicos de polígonos.

```sql
CREATE FUNCTION ST_Transform_resilient(
  g geometry,
  srid integer,
  density float DEFAULT 0.05
) RETURNS geometry AS $f$
  SELECT CASE
    WHEN isnot_point THEN  ST_Transform(  ST_Segmentize(g,density*(a+p)/2.0)  ,srid)
    ELSE  ST_Transform(g,srid)
    END
  FROM ( 
    SELECT CASE WHEN is_poly THEN SQRT(ST_Area(g)) 
                ELSE 0 END,
           CASE WHEN is_poly THEN ST_Perimeter(g)/3.5
                WHEN isnot_point THEN 2.0*ST_Length(g) END,
           isnot_point
    FROM ( SELECT GeometryType(g) ) t1(geomtype), LATERAL (
      SELECT CASE WHEN geomtype='POLYGON' OR geomtype='MULTIPOLYGON' THEN true ELSE false END AS is_poly,
         CASE WHEN geomtype='POINT' OR geomtype='MULTIPOINT' THEN false ELSE true END AS isnot_point
    ) t2
  ) t3(a,p,isnot_point)
$f$ LANGUAGE SQL IMMUTABLE;
```

**Comment by 0e1** [comment]
Aplicquei a função apenas no decode, por hora. Ver https://github.com/osm-codes/CO_new/commit/2f039094621b4a736ea3dfa203f44c9e0dda87ff.

Usei `density=0.005` para não visualizar falhas quando estiver na escala de metro.

Qual a melhor lib de https://github.com/AddressForAll/pg_pubLib-v1/tree/main/src para acomodar a `ST_Transform_resilient`?

**Comment by 0e1** [comment]
Ver https://github.com/osm-codes/GGeohash/issues/10.
