### ISSUE TITLE
Remover o lixo dos scripts

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/GGeohash#27]
o script https://github.com/osm-codes/GGeohash/blob/main/src/step04def-ini.sql
está com dezenas de blocos comentados por `/* .. */` , alguns até com falha de sintaxe.
Estes blocos só são necessários no git-branch e muito raramente nas transições de grandes mudanças.
Temos agora a Wiki oficial de documentação para documentar.
Alternativamente podemos usar a https://github.com/osm-codes/GGeohash/wiki para copiar/colar isso tudo temporariamente.

**Comment by 0e1** [comment]
Movi o conteúdo para https://github.com/osm-codes/GGeohash/wiki/step04def-ini.sql.
