### ISSUE TITLE
Coberturas em overlap e pontos centrais de quadrantes nomeados

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/GGeohash#5]
Movendo. Juntar (*merge*) esta *issue* na https://github.com/osm-codes/GGeohash/issues/9

----

* Coberturas em overlap: nova implementação, segundo conjunto de geocódigos que formam a cobertura de overlap, se sobreponto à "cobertura natural". Ver exemplo na grade BR, https://github.com/osm-codes/BR_new/issues/4

* Geocodigos de referência são sempre compativeis com o mosaico de jurisdições, e em certo sentido o tratamento é analogo ao overlap. Vide ["Guidance for shortening" do OLC](https://github.com/google/open-location-code/wiki/Guidance-for-shortening-codes), a estratégia é quase a mesma.

**Comment by 0e1** [comment]
O https://github.com/osm-codes/GGeohash/commit/350b5b12ed346b1db101a8cd363a782851fc661c ordena a tabela de coberturas de maneira que prefixos maiores tem preferencia. Acredito ser o suficiente para o _overlap_.

Exemplo em http://osm.codes/BR-RJ-RioJaneiro:

![screen](https://user-images.githubusercontent.com/41844788/196817938-7e529b95-1674-4737-9643-a62cea5cc17d.png)

**Comment by ppKrauss** [comment]
@0e1, ver discussão e requisitos adicionais em https://github.com/osm-codes/GGeohash/issues/9
